---
# defaults

jsbeautify: &jsbeautify
  indent_style: tab
  indent_size: 1
  preserve_newlines: true
  keep_array_indentation: true
  end_with_newline: true
  brace_style: collapse,preserve-inline
  max_preserve_newlines: 2

###############################

JavaScript:
  beautifiers:
    - JS-Beautify
    - ESLint
  << : *jsbeautify
  arrow_parens: always
  end_with_semicolon: true

JSON:
  beautifiers:
    - JS-Beautify
  << : *jsbeautify
